---
name: Dependency Updater

on:
  schedule:
    # Run every week 9:05 AM UTC (Monday at 1:00 AM PT)
    - cron: '05 9 * * 1'
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/.github/.github/workflows/go-updater.yml@go-updater-v1
    secrets: inherit
